<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Smart_Medc.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Services\AI\" />
    <Folder Include="Interfaces\Services\Appointments\" />
    <Folder Include="Interfaces\Services\DataSharing\" />
    <Folder Include="Interfaces\Services\Identity\" />
    <Folder Include="Interfaces\Services\Notifications\" />
    <Folder Include="Interfaces\Services\Organizations\" />
    <Folder Include="Interfaces\Services\Patients\" />
  </ItemGroup>

</Project>
