using AutoMapper;
using Smart_Medc.Application.DTOs.DataSharing;
using Smart_Medc.Domain.Entities.DataSharing;
using Smart_Medc.Domain.Entities.PatientModels;

namespace Smart_Medc.Application.Mappings
{
    public class DataSharingMappingProfile : Profile
    {
        public DataSharingMappingProfile()
        {
            CreateMap<DataShareCode, DataShareCodeDto>()
                .ForMember(dest => dest.Status,
                    opt => opt.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.AccessCount,
                    opt => opt.MapFrom(src => src.AccessLogs != null ? src.AccessLogs.Count : 0))
                .ForMember(dest => dest.SharedRecordsSummary,
                    opt => opt.MapFrom(src => src.RecordAccesses != null
                        ? src.RecordAccesses.Select(ra => ra.MedicalRecord.Title).ToList()
                        : new List<string>()));

            CreateMap<MedicalRecord, SharedMedicalRecordDto>()
                .ForMember(dest => dest.Date,
                    opt => opt.MapFrom(src => src.RecordDate))
                .ForMember(dest => dest.Category,
                    opt => opt.MapFrom(src => src.RecordType.ToString()))
                .ForMember(dest => dest.Doctor,
                    opt => opt.MapFrom(src => src.ProviderName ?? "Unknown"))
                .ForMember(dest => dest.Documents,
                    opt => opt.MapFrom(src => src.Documents != null
                        ? src.Documents.Where(d => !d.IsDeleted).ToList()
                        : new List<MedicalRecordDocument>()));

            CreateMap<MedicalRecordDocument, SharedDocumentDto>()
                .ForMember(dest => dest.Size,
                    opt => opt.MapFrom(src => src.FileSizeBytes))
                .ForMember(dest => dest.FileName,
                    opt => opt.MapFrom(src => src.OriginalFileName))
                .ForMember(dest => dest.DownloadUrl,
                    opt => opt.Ignore()); // Will be generated by controller with signed URL

            CreateMap<DataShareAccessLog, AccessLogDto>()
                .ForMember(dest => dest.OrganizationName,
                    opt => opt.MapFrom(src => src.Organization != null ? src.Organization.Name : "Unknown"));
        }
    }
}
